"""
Pipeline self-test for analyze_curves.py using SYNTHETIC curves with KNOWN ground truth
(MPL backbone + DropRelaxS lag + small noise).  This is NOT a scientific result (the truth
is generated by the same model family); it only verifies the analysis code runs and recovers
known quantities. Real science comes from real (held-out-generated) curves.
"""
import os, sys, json, csv, tempfile, shutil
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import engine as E

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- schedules (torch-free; mirror train.py protocol) ---
PEAK = 1.2e-3
ENDF = 0.1
WARM = 500
TOTAL = 8000
DECAY_START = 6000
WSDCON_TOTAL = 8000
WSDCON_DROP = 4000
STAGE2 = [0.5e-4, 1.0e-4, 2.0e-4, 4.0e-4, 8.0e-4]


def build_schedules():
    end = PEAK * ENDF
    S = {}
    S["cosine"] = E.cosine_lrs(TOTAL, PEAK, end, WARM)
    S["constant"] = E.const_lrs(TOTAL, PEAK, WARM)
    S["wsd"] = E.wsd_sqrt_lrs(TOTAL, DECAY_START, PEAK, end, WARM)
    S["wsdld"] = E.wsd_lrs(TOTAL, DECAY_START, PEAK, end, WARM)
    for s2 in STAGE2:
        S[f"wsdcon_{int(round(s2*1e5))}"] = E.two_stage_lrs(WSDCON_TOTAL, PEAK, s2, WSDCON_DROP, WARM)
    return S


class TR:
    PEAK = PEAK
    build_schedules = staticmethod(build_schedules)

# true constants per "scale" (lambda_slow shared/scale-invariant; amplitude grows with scale)
TRUE = {
    "s": dict(mpl=[3.0, 0.55, 0.50, 350.0, 2.0, 0.58, 0.64], kappa=0.6),
    "m": dict(mpl=[2.6, 0.60, 0.45, 440.0, 2.1, 0.60, 0.66], kappa=1.0),
    "l": dict(mpl=[2.35, 0.65, 0.43, 520.0, 2.0, 0.59, 0.63], kappa=1.4),
}
LAM_SLOW_TRUE = 20.0   # S-time rate (peak~1.2e-3 -> tau_steps=1/(lam*eta2) ~ 60..1000 steps, resolvable)


def synth_curve(etas, mpl_params, kappa, lam_slow, eta_peak, dLeq, step, seed):
    rng = np.random.default_rng(seed)
    L = E.mpl_loss(etas, *mpl_params)
    lag = kappa * eta_peak * dLeq * E.droprelaxS(etas, lam_slow)
    y = (L + lag)[step]
    y = y + rng.normal(0, 0.0008, size=y.shape)   # eval noise
    return y


def main():
    tmp = os.path.join(ROOT, "results", "curves_synth")
    if os.path.exists(tmp):
        shutil.rmtree(tmp)
    os.makedirs(tmp)
    scheds = TR.build_schedules()
    json.dump({k: v.tolist() for k, v in scheds.items()}, open(os.path.join(tmp, "schedules.json"), "w"))
    # dLeq/deta for the noise floor ~ derivative of floor vs eta; here just a positive constant per scale
    dLeq = 120.0
    eta_peak = TR.PEAK
    for sc, tv in TRUE.items():
        for name, etas in scheds.items():
            step = np.arange(0, len(etas), 20)
            if name.startswith("wsdcon"):   # dense sampling in the relaxation window (mirror train.py)
                fine = np.arange(WSDCON_DROP - 40, len(etas), 4)
                step = np.unique(np.concatenate([step, fine]))
            y = synth_curve(etas, tv["mpl"], tv["kappa"], LAM_SLOW_TRUE, eta_peak, dLeq, step, seed=hash((sc, name)) % 2**31)
            with open(os.path.join(tmp, f"{sc}_{name}.csv"), "w", newline="") as f:
                w = csv.writer(f); w.writerow(["step", "lr", "train_loss", "eval_loss"])
                for s, yy in zip(step, y):
                    w.writerow([int(s), float(etas[s]), float(yy), float(yy)])
    # run analyze_curves against the synthetic dir
    import analyze_curves as AC
    AC.CURVEDIR = tmp
    AC.OUT = tmp
    print(f"true lam_slow={LAM_SLOW_TRUE}, true kappa(s/m/l)={[TRUE[k]['kappa'] for k in TRUE]}")
    AC.main()
    rep = json.load(open(os.path.join(tmp, "REAL_CURVE_REPORT.json")))
    print("\n=== PIPELINE SELF-TEST CHECKS ===")
    ok = True
    for sc in TRUE:
        ps = rep["per_scale"][sc]
        sig = ps["signature"]
        # check: wsd residual >> cosine residual (the signature)
        cond_sig = sig.get("wsd", {}).get("max_abs", 0) > 2 * sig.get("cosine", {}).get("max_abs", 1e9)
        drs = ps["droprelaxS"].get("wsd", {})
        cond_r2 = drs.get("R2", 0) > 0.8
        print(f"  scale {sc}: wsd_maxabs={sig.get('wsd',{}).get('max_abs'):.4f} cosine_maxabs={sig.get('cosine',{}).get('max_abs'):.4f} "
              f"droprelaxS_R2(wsd)={drs.get('R2'):.3f} lam_fit={drs.get('lam'):.1f} | sigOK={cond_sig} R2OK={cond_r2}")
        ok = ok and cond_sig and cond_r2
    if "cross_scale_summary" in rep:
        cs = rep["cross_scale_summary"]
        print(f"  cross-scale avg delta={cs['avg_delta']*100:+.0f}% wins {cs['wins']}/{cs['n']}")
        ok = ok and cs["avg_delta"] < 0   # correction should help on synthetic-with-lag
    print(f"\nPIPELINE SELF-TEST: {'PASS' if ok else 'CHECK FAILED'}")


if __name__ == "__main__":
    main()
